dist: xenial
language: java
sudo: false
jdk: openjdk16
install: true
addons:
  sonarcloud:
    organization: thonecardoso
    token: 2ab32add289a8c4514ac7807929b99f96182eb9f
script:
  - mvn clean package sonar:sonar -P sonar
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache