dist: xenial
language: java
sudo: false
jdk: openjdk16
install: true
addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token: $SONAR_TOKEN
script:
  - mvn clean verify sonar:sonar -Psonar
#  - mvn clean package sonar:sonar -P sonar

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache