spring:
  datasource:
    url: jdbc:mariadb://${DATABASE_SERVER_NAME:localhost}:3306/bookstoremanager-dev?createDatabaseIfNotExist=true&useSSL=false
    username: ${DATABASE_USER_NAME:tc}
    password: ${DATABASE_USER_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com:
      thonecardoso: DEBUG
