spring:
  datasource:
    url: jdbc:h2:men:bookstoremanager-prod;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false


logging:
  level:
    com:
      thonecardoso: INFO